ProcessoSeletivTODOS.Clients.MVC/Controllers/PerfilController.cs
using ProcessoSeletivTODOS.Clients.MVC.ViewModel;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProcessoSeletivTODOS.Clients.MVC.Controllers
{
    public class PerfilController : BaseController
    {
        // GET: Perfil
        public ActionResult Index()
        {
            return View(new PerfilViewModel());
        }

        public ActionResult List()
        {
            return PartialView(ConsomeApi<List<PerfilViewModel>>("api/Perfil",Method.GET, null).Data);
        }

        [HttpPost]            
        public ActionResult Salvar(PerfilViewModel vmodel)
        {
            if (!ModelState.IsValid)
                return View("Index", vmodel);

            var parameters = new Dictionary<string, object>();
            parameters.Add("PerfilId", vmodel.PerfilId);
            parameters.Add("Descricao", vmodel.Descricao);


            IRestResponse<PerfilViewModel> response;
            if(vmodel.PerfilId > 0)
                response = ConsomeApi<PerfilViewModel>("api/Perfil", Method.PUT, parameters);
            else
                response = ConsomeApi<PerfilViewModel>("api/Perfil", Method.POST, parameters);

            if (response.StatusCode == System.Net.HttpStatusCode.OK || response.StatusCode == System.Net.HttpStatusCode.NoContent)
                SetNotificacaoSucesso("Perfil Adicionado com sucesso");
            else
                SetNotificacaoErro("Erro ao adicionar perfil !");

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var entity = ConsomeApi<PerfilViewModel>("api/Perfil/" + id.ToString(), Method.GET, null).Data;

            if(entity == null)
            {
                SetNotificacaoErro("Usuário indisponível ou inexistente !");
                return RedirectToAction("Index");
            }

            return View("Index", entity);
        }

        public ActionResult Delete(int id)
        {
            var response = ConsomeApi<PerfilViewModel>("api/Perfil/" + id.ToString(), Method.DELETE, null);

            if (response.StatusCode == System.Net.HttpStatusCode.OK || response.StatusCode == System.Net.HttpStatusCode.NoContent)
                SetNotificacaoSucesso("Perfil Excluído com sucesso");
            else
                SetNotificacaoErro("Erro ao excluir perfil !");

            return RedirectToAction("Index");
        }
    }
}

ProcessoSeletivTODOS.Clients.MVC/Views/Perfil/Index.cshtml
@model ProcessoSeletivTODOS.Clients.MVC.ViewModel.PerfilViewModel
@{
    ViewBag.Title = "Index";
}
<br />
<h3>
    Gerenciamento de Perfil 
</h3>
<br />
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" action="@Url.Action("Salvar","Perfil")" method="post" >
            @Html.HiddenFor(d => d.PerfilId)
            <div class="form-group">
                <label class="col-md-2 control-label">Descrição do Perfil</label>
                <div class="col-md-8">
                    @Html.TextBoxFor(d => d.Descricao, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Descricao, "", new { @class = "validation-message text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-8">
                    <button class="btn btn-sm btn-primary">
                        <i class="glyphicon glyphicon-save"></i> Salvar
                    </button>
                </div>
            </div>

        </form>
    </div>
</div>

<br />


@Html.Action("List","Perfil")

ProcessoSeletivTODOS.Clients.MVC/Views/Perfil/List.cshtml
@model IEnumerable<ProcessoSeletivTODOS.Clients.MVC.ViewModel.PerfilViewModel>
@{
    ViewBag.Title = "List";
}

@if (Model != null && Model.Count() > 0)
{

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Descrição</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.PerfilId</td>
                        <td>@item.Descricao</td>
                        <td style="text-align:right;" >
                            <a href="@Url.Action("Edit", new { id = item.PerfilId })" class="btn btn-xs btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a href="@Url.Action("Delete", new { id = item.PerfilId })" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

}