ProcessoSeletivTODOS.Clients.MVC/Controllers/UsuarioController.cs
using ProcessoSeletivTODOS.Clients.MVC.ViewModel;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProcessoSeletivTODOS.Clients.MVC.Controllers
{
    public class UsuarioController : BaseController
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View(new UsuarioViewModel());
        }

        public ActionResult List()
        {
            return PartialView(ConsomeApi<List<UsuarioViewModel>>("api/Usuario", Method.GET, null).Data);
        }

        [HttpPost]
        public ActionResult Salvar(UsuarioViewModel model)
        {
            if (model.UsuarioId > 0)
            {
                ModelState.Remove("Senha");
                ModelState.Remove("ConfirmaSenha");
            }

            if (!ModelState.IsValid)
                return View("Index",model);
            
            if(model.Senha != model.ConfirmaSenha && model.UsuarioId == 0)
            {
                model.Senha = "";
                model.ConfirmaSenha = "";
                ModelState.AddModelError("ConfirmaSenha", "As senhas não coincidem !");
                return View("Index", model);
            }
            
            if(model.Login.Contains(" "))
            {
                ModelState.AddModelError("Login", "O Login do usuário não deve conter expeços !");
                return View("Index",model);
            }
            
            var parameters = new Dictionary<string, object>();
            parameters.Add("Ativo", model.Ativo);
            parameters.Add("Login", model.Login);
            parameters.Add("Email", model.Email);
            parameters.Add("DataCadastro", model.DataCadastro.ToShortDateString());
            parameters.Add("UsuarioId", model.UsuarioId);
            parameters.Add("Senha", model.Senha);

            if (model.UsuarioId > 0)
                ConsomeApi<UsuarioViewModel>("api/Usuario", Method.PUT, parameters);
            else
                ConsomeApi<UsuarioViewModel>("api/Usuario", Method.POST, parameters);

            if(!HasError)
                SetNotificacaoSucesso("Usuário salvo com sucesso !");

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            var vmodel = ConsomeApi<UsuarioViewModel>("api/Usuario/" + id.ToString(), Method.GET, null).Data;
            vmodel.ConfirmaSenha = vmodel.Senha;
            return View("Index", vmodel );
        }


        public ActionResult Delete(int id)
        {
            ConsomeApi<UsuarioViewModel>("api/Usuario/" + id.ToString(), Method.DELETE, null);
            SetNotificacaoSucesso("Usuário excluído com sucesso !");
            return RedirectToAction("Index");
        }
    }
}

ProcessoSeletivTODOS.Clients.MVC/Views/Usuario/Index.cshtml
@model ProcessoSeletivTODOS.Clients.MVC.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Index";
}

<h3>Gerenciamento de Usuários</h3>
<br />
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" action="@Url.Action("Salvar","Usuario")" method="post" >
            
            @Html.HiddenFor(f => f.DataCadastro)
            @Html.HiddenFor(d => d.UsuarioId)

            <div class="form-group">
                <label class="control-label col-md-2">
                    @Html.LabelFor(d => d.Login)
                </label>
                <div class="col-md-8">
                    @Html.TextBoxFor(d => d.Login, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Login, "", new { @class = "validation-message text-danger" })
                </div>
            </div>       

            <div class="form-group">
                <label class="control-label col-md-2">
                    @Html.LabelFor(d => d.Email)
                </label>
                <div class="col-md-8">
                    @Html.TextBoxFor(d => d.Email, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Email, "", new { @class = "validation-message text-danger" })
                </div>
            </div>       

            <div class="form-group">
                <label class="control-label col-md-2">
                    @Html.LabelFor(d => d.Ativo)
                </label>
                <div class="col-md-8">
                    @Html.CheckBoxFor(d => d.Ativo)
                    @Html.ValidationMessageFor(d => d.Ativo, "", new { @class = "validation-message text-danger" })
                </div>
            </div>             

            @if (Model.UsuarioId == 0)
            {
                
                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(d => d.Senha)
                    </label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(d => d.Senha, "", new { @class = "form-control", type = "password" })
                        @Html.ValidationMessageFor(d => d.Senha, "", new { @class = "validation-message text-danger" })
                    </div>
                </div>  


                <div class="form-group">
                    <label class="control-label col-md-2">
                        @Html.LabelFor(d => d.ConfirmaSenha)
                    </label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(d => d.ConfirmaSenha, "", new { @class = "form-control", type = "password" })
                        @Html.ValidationMessageFor(d => d.ConfirmaSenha, "", new { @class = "validation-message text-danger" })
                    </div>
                </div>   
            }
            <div class="form-group">
                <label class="control-label col-md-2">
                    
                </label>
                <div class="col-md-8">
                    <button class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-save"></i>
                        Salvar
                    </button>
                </div>
            </div>

        </form>
    </div>
</div>

@Html.Action("List")

ProcessoSeletivTODOS.Clients.MVC/Views/Usuario/List.cshtml
@model IEnumerable<ProcessoSeletivTODOS.Clients.MVC.ViewModel.UsuarioViewModel>

@{
    ViewBag.Title = "List";
}

@if (Model != null && Model.Count() > 0)
{
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped" >
            <thead>
                <tr>
                    <th>Login</th>
                    <th>Email</th>
                    <th>Data Cadastro</th>
                    <th>Ativo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Login</td>
                        <td>@item.Email</td>
                        <td>@item.DataCadastro</td>
                        <td>@(item.Ativo ? "Ativo" : "Inaivo" )</td>
                        <th style="text-align: right;" >
                            <a href="@Url.Action("Editar", new { id = item.UsuarioId })" class="btn btn-xs btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a href="@Url.Action("Delete", new { id = item.UsuarioId })" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

}